version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations --no-input &&
                    python manage.py migrate --no-input &&
                    python manage.py initiate_admin &&
                    python manage.py collectstatic --no-input &&
                    gunicorn hrmis.wsgi:application --bind 0.0.0.0:3000"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 3000
    env_file:
      - .env
    network_mode: host

volumes:
  static_volume:
  media_volume: